version: "3.9"

services:
  # =========================
  # DEV
  # =========================

  client-dev:
    profiles: ["dev"]
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    container_name: sentinel-front-dev
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - sentinel-front

  back-dev:
    profiles: [ "dev" ]
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    container_name: back-dev
    restart: always
    env_file:
      - ./back/.env
    volumes:
      - ./back:/back
      - /back/node_modules
    ports:
      - "3001:3001"
    depends_on:
      mysql-sentinel:
        condition: service_healthy

  mysql-sentinel:
    profiles: ["dev"]
    image: mysql:8
    container_name: mysql-sentinel
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sentinel_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-sentinel-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -ppassword --silent"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s

  # =========================
  # PROD
  # =========================
  client:
    profiles: ["prod"]
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: sentinel-front-app
    ports:
      - "80:80"
    networks:
      - sentinel-front
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/ || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  api:
    profiles: ["prod"]
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: sentinel-back
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      mysql-prod:
        condition: service_healthy
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3001/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - sentinel-back

  mysql-prod:
    profiles: ["prod"]
    image: mysql:8
    container_name: mysql-prod
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Europe/Paris
    volumes:
      - mysql-prod-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u${MYSQL_USER} -p${MYSQL_PASSWORD} --silent" ]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s
    networks:
      - sentinel-back

volumes:
  mysql-sentinel-data:
  mysql-prod-data:

networks:
  sentinel-front:
    driver: bridge
  sentinel-back:
    driver: bridge