version: "3.9"

services:
  # DEV
  client-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: sentinel-front-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - sentinel-front

  # PROD
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentinel-front-app
    ports:
      - "80:80"
    networks:
      - sentinel-front
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/ || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  sentinel-front:
    driver: bridge
