global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "sentinel-node"
    static_configs:
      - targets: ["82.165.92.40:9100"]

  - job_name: "product-node"
    static_configs:
      - targets: ["82.165.46.201:9100"]
