apiVersion: 1
groups:
  - orgId: 1
    name: nginx-rules
    folder: "Nginx Alerts"
    interval: 10s
    rules:
      - uid: "nginx-20req-10s"
        title: "Pormanov Ddos"
        condition: C
        data:
          - refId: A
            datasourceUid: loki
            queryType: range
            relativeTimeRange:
              from: 10s
              to: 0s
            model:
              expr: "count_over_time({job=\"nginx\"}[10s])"
              interval: ""
              datasource:
                type: loki
                uid: loki
          - refId: B
            datasourceUid: __expr__
            model:
              type: threshold
              conditions:
                - evaluator:
                    type: gt
                    params: [20]
                  operator:
                    type: and
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              label: ""
              refId: B
        noDataState: NoData
        execErrState: Alerting
        for: 0s
        annotations:
          summary: "Jean Pormanov tente de vous attacquer depuis l'enfer"
        labels:
          severity: warning